### ISSUE TITLE
FromUtf8Error

### ISSUE THREAD

**Issue by arozans** [kdheepak/taskwarrior-tui#13]
While scrolling through my tasks (some of them contain polish chars) an exception is being thrown:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [10, ... 10], error: Utf8Error

`task export` for the problematic task:

```
[
{"id":158,"description":"AAAA-1954 | [SPIKE] Dogadanie się z XXXXX aby CSVki YY","entry":"20200505T102512Z","jiradescription":"*Kryteria akceptacyjne*: ^kiedy zadanie uważamy za zakończone^\r\n- Ustalimy jak wygląda plik co jest w nagłówku itp.\r\n- Ustalimy  do których wrzucimy CSVki YY.\r\n- Ustalimy co z podpisem CSVki.\r\n","jiraid":"AAAA-1954","jiraissuetype":"Story","jirastatus":"Blocked","jirasummary":"[SPIKE] Dogadanie się z XXXXX aby CSVki YY","jiraurl":"https:\/\/jira.com\/browse\/YYYY-1954","modified":"20201006T060019Z","priority":"L","project":"SPIKE","status":"pending","tags":["jira","work"],"uuid":"ce430ec8-349b-4c8e-80e3-5f99ad81f831","annotations":[{"entry":"20201005T164609Z","description":"@aaa.bbb - Pogoniłem w mailu, ale bez odpowiedzi."},{"entry":"20201005T164720Z","description":"https:\/\/jira.com\/browse\/AAAA-1954"}],"urgency":-2.15068}
]
```

**Comment by kdheepak** [comment]
Thanks for the bug report. What is the operating system you are using?

**Comment by arozans** [comment]
Ubuntu 19.10

**Comment by kdheepak** [comment]
Interestingly I'm not able to reproduce the panic.

![Screen Shot 2020-10-08 at 3 22 07 PM](https://user-images.githubusercontent.com/1813121/95514995-249f1e80-097a-11eb-80a5-f99059a8e862.png)

Are you sure you are using the latest version of `taskwarrior-tui`? Because this is similar to an issue we had earlier: https://github.com/kdheepak/taskwarrior-tui/issues/4

I would not be surprised if there's another issue though. I'm making a new release that will prevent the panic but won't display task details in that case. 

But I would like more information from you to figure out what is going on. Can you share this task from your `pending.data` file. You can file your `pending.data` file in this location by default: `~/.task/pending.data`. If you have changed it that information will be located in your `~/.taskrc` file.

**Comment by arozans** [comment]
Okay, i've found the culprit. One of my task, when exported via "task export" contains the word "odpalić". But when I show details of that task with "task info" it shows that particular word as  "odpali�" (last char is not rendered correctly). I can confirm that's the reason of the panic - when i delete this one char form pending.data and undo.data of that task, the problem disappears.

So this one char must be somehow encoded incorrectly (?). Not sure who is to blame for that - that particular task was importer via bugwarrior from jira.

When creating a new task using the same description as the one that caused the problem, everything works fine (your tui shows question mark and no panic occurs) - so that faulty encoding must be already fixed during copy/paste.

**Comment by kdheepak** [comment]
Nice find. That does seem like it wasn't encoded differently. I'm assuming everything is utf8, but I didn't check what taskwarrior assumes. It is possible that taskwarrior is is just passing bytes around.
 
In either case, I think taskwarrior-tui should never segfault. Does it still segfault with the most recent version?

**Comment by kdheepak** [comment]
Alternatively, if you can share your `pending.data` after stripping away personal information, I can look into this more.

**Comment by arozans** [comment]
I can confirm that with the most recent version the issue is resolved. Thanks!
