### ISSUE TITLE
Is there a way to scroll the task info?

### ISSUE THREAD

**Issue by k4y4k** [kdheepak/taskwarrior-tui#150]
Hey there :wave: 

I bring in issues and PRs from GitHub via `bugwarrior`. This means that they have a lot of metadata to them (especially PRs) and are much, much too tall for the lower half of my screen to show.

I looked in the docs and couldn't find an answer. Currently I work around the issue by pressing `e` to edit and thus scroll down with vim, but is there any way to do so in taskwarrior-tui?

Cheers!

**Comment by kdheepak** [comment]
Thanks for opening an issue. This is good feature request. Currently there is not but I’ll look to add this feature!

**Comment by kdheepak** [comment]
I have a branch and a PR where I've added the scroll feature to it. If you want to try it out, you can build from source or download one of the artifacts and test it out. (`Ctrl+e` for scroll down and `Ctrl+y` for scroll up). Once I add some documentation, I'll merge it. I'll plan to do it by the end of the day.

**Comment by k4y4k** [comment]
Hang on, I'm building from source now as I type this...

**Comment by kdheepak** [comment]
It’s recommend using the latest commit on the `master` branch to test this.

**Comment by k4y4k** [comment]
Yeah, that's what I'm doing lmao

**Comment by kdheepak** [comment]
Great! Currently, it’s not key configurable. But I’ll have to fix that in a separate PR.

**Comment by k4y4k** [comment]
nah the lack of configurable keys is fine tbh, no wakkas (no worries)

**Comment by kdheepak** [comment]
If you run `cargo run` it makes a debug build and that can be quite laggy. But you can add the `—release` flag to it and it should be as snappy as the releases from various package managers and releases. 

However, I do think there’s lots of performance improvements to be made. Right now I’m exploring the features that I think are useful and I’m using this as a experimenting / learning opportunity in some ways. I have plans for a refactor where I’ll take a closer look at dealing with performance.

**Comment by k4y4k** [comment]
Before right now, I was using the version packaged in the AUR. It's *excruciatingly* laggy. I'm talking "takes 7-800ms to add or remove characters from the `Filter tasks` pane" laggy. Scrolling is a one-by-one affair, because if I hold down :arrow_up: / :arrow_down: I *will* overshoot and have to spend ages going back. having a seperate tmux pane ready for `task minimal | grep -i [whatever]` is a lifesaver for searching. 

But back on topic (I can open another issue for this): `ctrl+e` and `ctrl+y` work fine!

Ran `cargo run --release` (and `--verbose` because I'm *that* kind of person :joy:). Thank you so much!

**Comment by k4y4k** [comment]
I don't know the ins and outs of your GitHub CI setup, but when can I expect this to bump up the release number?

**Comment by kdheepak** [comment]
Is `cargo run —release` as slow and laggy as the AUR release? How many tasks do you have in your default `next` filter?

**Comment by k4y4k** [comment]
A... lot :sweat_smile: 

518, if I understand `task next`'s footer correctly.

**Comment by kdheepak** [comment]
Interesting! I’ll add a lot of fake tasks and test on my machine. I’m sure I can make some simple changes to improve performance now.

**Comment by k4y4k** [comment]
good luck! :+1:

**Comment by kdheepak** [comment]
I'm able to replicate it and I know one cause of the problem. Unfortunately the fix is not as straightforward as I thought. 

The issue is that `taskwarrior-tui` shells out to `taskwarrior` to get the task details and this happens as and when you scroll. I'm not sure exactly why it causes a lag only when there are a larger number of tasks though (further investigation is required). 

One solution is to cache the task details. I tried caching ahead of time, but this currently causes `taskwarrior-tui` to take a long time to start up because it happens synchronously. I would have to do this in a background thread or in a `async` manner. I'll have to address this properly during the refactor I mentioned earlier.

For now, I've implemented a hack. I'm caching the task details the first time you scroll to a task. This means you'll still experience a lag as you scroll but only the first time. The next time onwards it is fairly snappy and there's no overshooting. It doesn't really help all that much because you'll have to scroll through 500 odd tasks the first time you start up `taskwarrior-tui` but it is better than what is currently implemented I guess.

I'll open a new issue to track performance issues. Maybe the refactor needs to happen sooner than I thought :)

**Comment by k4y4k** [comment]
Good detective work there my dude :eyes:

Generally, the first thing I do anyway is add `-BLOCKED` to the filter and `project.not` 1 or 2 projects I don't need to see (but do need to track), which cuts down the task list considerably. Scrolling through this list once to get things cached is fine by me

**Comment by kdheepak** [comment]
You can try the latest commit on the `master` branch to see if that helps alleviate the pain a little!

**Comment by k4y4k** [comment]
OK, building now...

**Comment by k4y4k** [comment]
>  I'm not sure exactly why it causes a lag only when there are a larger number of tasks though (further investigation is required).

`task` itself might be slowing down on invoking `info` with a lot of tasks (and a history as large as mine). For reference, my undo.data is several MB big. That might not bother `task` but it could be something to consider?  https://www.reddit.com/r/taskwarrior/comments/llu7pa/slow_to_load_due_to_too_much_info_in_undodata/

**Comment by k4y4k** [comment]
Wow! Things are immediately 1000% better oh my god. Messing with the filter is snappy. Scrolling is snappy! Everything is fast!! 

Thank you again!

**Comment by kdheepak** [comment]
> For reference, my undo.data is several MB big.

Ah that's interesting. That is possible to cause things to slow down a lot because the current implementation is shelling out and calling `task ...` a lot for various things. And because EVERYTHING happens synchronously small delays will add up. If only I had the foresight to use `async` to begin with 😓. But the refactor will likely go in that direction!

> Wow! Things are immediately 1000% better oh my god. Messing with the filter is snappy. Scrolling is snappy! Everything is fast!!

I'm glad things are a little better! And to answer your question from earlier, I'll be making a new release in a few days. I want to get a couple more features into this release. It's going to be a big one :)

**Comment by kdheepak** [comment]
I've opened an issue to track performance related issues: https://github.com/kdheepak/taskwarrior-tui/issues/154. I'll post comments and link related PRs to there going forward.

**Comment by kdheepak** [comment]
I've made a new release that has the scrolling feature as well as other improvements related to task information: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.13.0.
