### ISSUE TITLE
Can I change report columns?

### ISSUE THREAD

**Issue by arozans** [kdheepak/taskwarrior-tui#17]
Project column alongside with tags column are important in my workflow. It looks like those columns are not supported out of the box with you tui. Is there a way to choose what columns are shown?

I know i can see those values in the details view of the task at the bottom of the screen, but I would love to see those columns for all tasks in the report view (upper part of the screen).

Thanks.

**Comment by kdheepak** [comment]
Thanks for opening an issue! `taskwarrior-tui` uses the columns and labels that are in your `~/.taskrc`'s `report.next.columns` and `report.next.labels` attributes. And I've updated it now to show tags and projects correctly. You can try it out in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.6.12. Let me know if it doesn't work the way you expect or if anything else comes up.

**Comment by arozans** [comment]
Thanks for such a quick change! I can confirm that in the newest release tags and projects appeared in report! Thanks.

**Comment by arozans** [comment]
But now there is another issue :) Maybe task descriptions should be truncated/wrapped so that the remaining columns also show up? (I need to zoom out and make my font rather small to see my last "urgency" column right now). There is also quite a big gap between "Project" columnd and "Tag" column, is there a reason for that?

**Comment by kdheepak** [comment]
> task descriptions should be truncated/wrapped

Right now, it uses a constraint solver that uses the width of the content to decide what the width of the columns should be. So long descriptions cause issues. I've thought about wrapping and it would be nice to have, but not sure what a nice implementation of that looks like. I'll have to do more thinking / experimenting to see how that works out. 

I think truncation should be straightforward, and I can implement that as a temporary fix.

> There is also quite a big gap between "Project" columnd and "Tag" column, is there a reason for that?

I should be able fix this fairly easily. I think the reason is that even empty columns occupy non zero width in `taskwarrior-tui`. 

The whole column width calculator was kind of a hack and I'm going to have to redo it properly. I'll open a new issue for that.

**Comment by kdheepak** [comment]
Can you try https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.7.0? I think it should make thing better.

**Comment by arozans** [comment]
Yes, it's much better.
