### ISSUE TITLE
Add to macOS homebrew

### ISSUE THREAD

**Issue by 12-Seconds** [kdheepak/taskwarrior-tui#21]
Would it be possible to add this to homebrew on macOS?

**Comment by kdheepak** [comment]
Great idea! Yes, it should be possible. I'll look into it.

**Comment by kdheepak** [comment]
I've made a PR to homebrew-core: https://github.com/Homebrew/homebrew-core/pull/63373.

**Comment by kdheepak** [comment]
You can now install using `brew install taskwarrior-tui`. I've also set up a github action, so that when a new version is tagged here it'll open a PR on homebrew-core automatically. When homebrew-core maintainers merge the PR, the formula will be ready to install.

You can find the latest formula here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/taskwarrior-tui.rb

**Comment by gbstan** [comment]
This is amazing! The current version on brew is 0.8.0. Are we sure the updates are working?

**Comment by kdheepak** [comment]
If you check now, as of about 3 hours ago, the latest version is v0.8.7. Homebrew formula update PRs are all manually merged, so there's likely always going to be a little bit of a delay, but they should be merged within a day or so of release.
