### ISSUE TITLE
report.next.columns is ignored 

### ISSUE THREAD

**Issue by desbma** [kdheepak/taskwarrior-tui#224]
I have this in my `~/.taskrc`:
```
report.next.columns=id,start.age,depends,priority,project,tags,wait.remaining,scheduled.relative,due.relative,until,recur,description.truncated_count,urgency
report.next.labels=ID,Active,Deps,P,Project,Tag,Wait,Sched,Due,Until,Recur,Description,Urg
```
My default filter is also changed to `status:pending or status:waiting`, but that is correctly handled now (see #92).

However taskwarrior-tui ignores the added columns (ie. `Wait` or `Recur`).

- Operating System: Arch Linux
- Installation: https://archlinux.org/packages/community/x86_64/taskwarrior-tui/
- taskwarrior-tui version: `0.13.22-1`
- task version: `2.5.3-1`

**Comment by kdheepak** [comment]
Thanks for opening the issue! I've added support for `wait.remaining` and `recur` but there might be other column names that are not supported. If you run into any of them or find the full list of supported column names let me know and I'll update the tui to support them. Some of them might be an easier fix than others. Right now, `recur` displays `monthly` instead of `P30D` for example and that's not a straightforward feature to add.

**Comment by desbma** [comment]
Thanks, I tested your PR and that solves my issue. As you noted the recurrence is displayed a bit differently, but this is a minor difference, I can live with that.

Thanks again for the quick fix.

**Comment by apkawel** [comment]
FWIW, for the long-term roadmap, it would be nice if the display/report in the tui fully supported column modification. I ran into the same issue as @desbma.
