### ISSUE TITLE
Crash when project name contains dot and then more than certain count of characters

### ISSUE THREAD

**Issue by idevat** [kdheepak/taskwarrior-tui#341]
**Describe the bug**
Taskwarrior-tui crashes when you try add task e.g. `test project:a.1abcd2abcd3abcd4abcd5`

**To Reproduce**

* have no task in the database (complete clean `data.location`)
* open taskwarrior-tui: `~ $ taskwarrior-tui`
* press `a` to add task
* put `test project:a.1abcd2abcd3abcd4abcd5` and press enter

Taskwarrior-tui crashes with following message:
```sh
Backtrace (most recent call first):
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "./csu/../csu/libc-start.c", line 409, in __libc_start_main_impl

The application panicked (crashed).
  byte index 23 is out of bounds of `1abcd2abcd3abcd4abcd5`
in src/pane/project.rs, line 151
thread: main
```
**Environment (please complete the following information):**

- Operating System: Linux
- Installation: github releases
- taskwarrior-tui version:  0.15.1
- task version: 2.6.1

**Additional context and information**
When you run `task` after the crash you get expected result:
```sh
~ $ task

ID Age  Project                 Description Urg 
 1 4min a.1abcd2abcd3abcd4abcd5 test           1

1 task
```
When I run `taskwarrior-tui` again it redraws screen and crashes again with backtrace as above.

With some slight modifications of project it works well:
  *  `test project:a.1abcd2abcd3abcd4abcd` - one character shorter
  * `test project:a1.abcd2abcd3abcd4abcd5` - dot is moved one character right
  * however, this crashes: `test project:a1.abcd2abcd3abcd4abcd5a` - added one character on the end of previous^

**Comment by cionx** [comment]
I have encountered the same problem. I think the problem lies in the following piece of code:

https://github.com/kdheepak/taskwarrior-tui/blob/850ae7fbfc8c3b6425a24eb5caeff2159cc30ca4/src/pane/project.rs#L127-L132

It seems to me that the lines in `data` have a maximal length of 80 characters, which can lead to unexpected line breaks when project names becomes too long. I suspect this behavior comes from the variable `defaultwidth` in taskrc, whose standard value is `80`. When `defaultwidth` is set to `0` (so that lines can have unlimited length) then the problem doesn’t occur for me in 0.15.

**Comment by kdheepak** [comment]
Can you try v0.16.0? It shouldn’t crash any more.

**Comment by cionx** [comment]
Yes, both of the following work without crash:

- 0.16.0
- 0.15.0 with `defaultwidth=0` in `taskrc`

**Comment by kdheepak** [comment]
Interesting. Thanks for sharing that information about `defaultwidth`. In v0.16.0, I removed the all the code that handles parsing of the task summary, since I thought it was quite brittle. I’ll think about what to do going forward. It would be nice to generate the task summary data without parsing the output from the`task summary` command line.

**Comment by idevat** [comment]
@kdheepak Version 0.16.0 works without crash for me. Thanks!
