### ISSUE TITLE
Reset filter?

### ISSUE THREAD

**Issue by simonmeggle** [kdheepak/taskwarrior-tui#356]
Hi, 

I am somehow missing a way to reset a filter I ahve applied. 
The only way I see today is to press `/` again and edit the filter again. 

Would it be possible to add a hotkey to reset the filter to the default which is loaded on startup? 
Thanks for the tool!
Simon

**Comment by kdheepak** [comment]
Hi. While you are editing the filter, `Ctrl-r` should reset the filter to the original value defined by your taskwarrior configuration. 

https://github.com/kdheepak/taskwarrior-tui/blob/3cb54b1700ec812ac4eb6e3c2d5484116c282644/src/app.rs#L3264-L3272

This is not documented though, since I wasn't sure if this was something I wanted to keep / if I wanted to change the keybinding for this. Specifically, I've been debating using `ESC` when editing the default filter to reset the filter string. Hitting `Enter` will update the filter string as it does right now.

See this thread for more information https://github.com/kdheepak/taskwarrior-tui/issues/198

**Comment by kdheepak** [comment]
I decided to go ahead and change the behavior on <kbd>esc</kbd>, adding a configuration option for old behavior. Thanks for opening the issue, this feature will be available in the next release.

**Comment by kdheepak** [comment]
I made a new release with this feature: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.17.0
