### ISSUE TITLE
Provide error details to user, e.g. when no tasks are displayed

### ISSUE THREAD

**Issue by bradyt** [kdheepak/taskwarrior-tui#366]
I think there's been a number of issues on this project reported as "no tasks displayed". In other words, their issue report could be summarized as the following:

```
╭Task|Projects|Calendar────────────────╮
│                                      │
│                                      │
╰──────────────────────────────────────╯
╭Task not found────────────────────────╮
│                                      │
│                                      │
╰──────────────────────────────────────╯
╭Filter Tasks──────────────────────────╮
│status:pending -WAITING limit:page    │
╰──────────────────────────────────────╯
```

Presumably, once you have the data needed to reproduce, and open up the app with some debugging tools running, you get more helpful information like an exception and trace.

Could you start to expose some of that in some general way? I'm not sure where this tends to happen, if it happens as you parse or display the output of `task export`, and if you could have an overarching catch of these, and display some deliberate hint in the UI. Maybe it could be as generic as "an exception occurred while parsing your task data". Potentially you could display a particular failing task's json.

Hmm, or there could simply be a `taskwarrior-tui-error.log` file? But maybe the UI could still hint that something was added to the file. I guess an error log file could be a good place to send and format exceptions, I don't know if there's an idiom for apps to log traces. Just overwrite some `taskwarrior-tui-error.trace` file? Maybe recording trace for user is a bit less idiomatic.

**Comment by kdheepak** [comment]
The general problem is that errors occur all the time when running the `task` subprocess. For example, when typing the filter `(status:pending or status:waiting) pro` `taskwarrior` throws an error and returns `Mismatched parentheses in expression`.

```
$ task rc.json.array=on rc.confirmation=off rc.report.next.filter='(status:pending or status:waiting) pro' export next                                                                                                                                     
Mismatched parentheses in expression
```

But the filter `(status:pending or status:waiting) project:colortask` is a valid filter string. 

```
$ task rc.json.array=on rc.confirmation=off rc.report.next.filter='(status:pending or status:waiting) project:colortask' export next
[
{"id":10,"description":"Support color for tasks based on your .taskrc","due":"20210210T070000Z","entry":"20201021T065120Z","estimate":"30","modified":"20210216T100811Z","project":"colortask","status":"pending","uuid":"f8470e92-0286-4b85-91f4-acf6bf693f6c","annotations":[{"entry":"20201021T065519Z","description":"Started task"},{"entry":"20201021T065522Z","description":"Stopped task"}],"tags":["COLOR"],"urgency":14.8}
]
```

And users may type `pro` and wait. This error is conveyed through the color of the filter command line border. This is the default:

![Screen Shot 2022-01-11 at 2 13 01 PM](https://user-images.githubusercontent.com/1813121/149022367-3845d825-261f-43d8-91ac-54cdee207527.png)

This is when `task export` is returning an error:

![Screen Shot 2022-01-11 at 2 13 49 PM](https://user-images.githubusercontent.com/1813121/149022475-9cb2f4c1-44ea-4d06-942f-4948a57d5227.png)

If you try to hit enter when there's an error, a error window opens showing you the error that occurred.

![Screen Shot 2022-01-11 at 2 15 01 PM](https://user-images.githubusercontent.com/1813121/149022638-3c3ed550-6ea8-4644-a51c-852dfa6fba54.png)

If I put this in a log file, this would occur all the time.

Also, sometimes there's no tasks shown because the filter is too specific, and that's a valid state of the program to be in. So I'm not sure what the best way to handle errors is yet.

**Comment by kdheepak** [comment]
I changed it to show this dialog box when unable to parse the data returned by taskwarrior:

![image](https://user-images.githubusercontent.com/1813121/149026628-3abbc24e-524f-4f98-8303-588d3bba0412.png)

**Comment by kdheepak** [comment]
I made a new release that contains this feature: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.18.0

**Comment by bradyt** [comment]
Looks great!
