### ISSUE TITLE
How improves it perform speed?

### ISSUE THREAD

**Issue by agent-kimbley** [kdheepak/taskwarrior-tui#413]
When I open it hit command such as 'j' 'k',I need waiting for second
Is there for itself problem or my computer capability?

**Comment by kdheepak** [comment]
Hmm. Does it wait a second even if the task detail view is closed? How many tasks do you have?

**Comment by agent-kimbley** [comment]
12453 about at all,300 for +PENDING

**Comment by kdheepak** [comment]
I just ran a test with about a 1000 tasks in the PENDING and it doesn't seem to slow down for me. I think your `12453` tasks in total is causing a problem because `taskwarrior-tui` calls `task export` to get the data.

Can you run `time task export` and share how long it takes to run and return that output?

Also, you can try adding the following in your `.taskrc` file:

```
uda.taskwarrior-tui.tick-rate=10000
```

The default tick rate is 250ms, but if you change it to 10s then it shouldn't run `task export` as often.

**Comment by agent-kimbley** [comment]
real 0m0.347s
user 0m0.209s
sys 0m0.122s

**Comment by agent-kimbley** [comment]
real 0m2.254s
user 0m1.484s
sys 0m0.341s
