### ISSUE TITLE
Choose which report to show in "Task" View

### ISSUE THREAD

**Issue by b-boehne** [kdheepak/taskwarrior-tui#52]
**Description**

The main 'task' view seems to show the `next` report, but when changing the columns and labels via `.taskrc` the changes are not reflected in the tui.

**Solution**

A context menu to choose which report to show in the main view would be best, plus a config value to choose the default.   
As this may be much work, just reflecting the `next` report completely with all columns and labels would be another solution.

**Additional context**
Here's the changes in my `.taskrc` which should be reflected:
```
# attribute issue (number)
uda.issue.type=numeric
uda.issue.label=Issue

# attribute person
uda.person.type=string
uda.person.label=Person

# add custom attributes to 'next' report
report.next.columns=id,start.age,entry.age,depends,priority,project,issue,person,tags,recur,scheduled.countdown,due.relative,until.remaining,description,urgency
report.next.labels=ID,Active,Age,Deps,P,Project,Issue,Person,Tag,Recur,S,Due,Until,Description,Urg
```

FYI: If I find the time, I may just open a PR myself. This seems like a good project to learn about rust :)

**Comment by kdheepak** [comment]
Nice find! I'm implemented it in the linked PR. Here's what it looks like now :)

![Screen Shot 2020-11-10 at 12 51 11 PM](https://user-images.githubusercontent.com/1813121/98726210-6d6c3d80-2353-11eb-9486-827a17fa6e5e.png)

I debated whether letting you do it, since it was super straight forward, but I expect a refactoring coming up, so didn't want to bother you with it. 

Yeah, I think it is a good project to learn rust since it is a small enough project. This is also my first open source project in rust, so I'm more than happy to get feedback or comments on the codebase if you happen to go through it.

**Comment by b-boehne** [comment]
Wow that was quick, thanks so much :)
