### ISSUE TITLE
Implement command history

### ISSUE THREAD

**Issue by kdheepak** [kdheepak/taskwarrior-tui#84]
**Description**

It would be nice to have a command history for modifications / annotations etc

**Comment by C-Fergus** [comment]
If commands executed in TTUI were added to the users history, maybe by always executing them externally of the app with `:!task`, the history could be searched for commands that begin with `$ task`. This would allow task functions used outside of TTUI to also be accessed and vice versa.

I don't know if executing all task commands externally poses a security risk or if this should be a configurable option instead of a default to avoid cluttering the history of someone who prefers only the commands they executed in their prompt to be recorded.

**Comment by kdheepak** [comment]
That is an interesting idea. I think executing a subprocess in a program wouldn't add commands to a shell history though. We'd have to call a bash function (`history -s $task_cmd` or something like that) to add to shell history manually. I'm sure there's similar functions for `zsh` and `fsh` shells for this feature. I'll look into it.

I agree that it should default to `off`. I'd also really like to add history within the app itself, I think that would be very nice. Initially I was thinking I'd have to store history separately, but you've just given me the idea to use the command history from the shell and filter out the task subcommands. I'll experiment with this more.

**Comment by C-Fergus** [comment]
`fsh` doesn't have an easy method like `bash`, I think the easiest way is to copy the history, append the command to the copied file, and then merge the copied file back with the original. I didn't think about different shells when I suggested this method. Writing to TTUI's own history file as you suggested, or at least falling back to a history file for unknown or clunky shells might be best.

**Comment by kdheepak** [comment]
The latest release should support history. There's separate history files that `taskwarrior-tui` uses. It's stored in xdg config directories. See http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html for more information. On my mac, `~/.config/taskwarrior-tui/filter.history` and `~/.config/taskwarrior-tui/command.history` contain the history of filters and commands used. You can use the up and down across when editing a filter or command prompt to scroll through the history.
